### ISSUE TITLE
PMS-Question Anser-Second rating answer is not working correctly

### ISSUE THREAD

**Issue by o0alvin0o** [horilla-opensource/horilla#386] opened 2024-11-13 16:14 UTC
# Bug Report

## Description

From the second rating answer, it will not work correctly. You can not rate anything other than first rating anwser

## Steps to Reproduce

1. Create a question template with more than two questions type Rating.
2. Assign this template to an employee
3. Emloyee tries to anwser the second rating question
## Expected Behavior

Answer normally

## Actual Behavior

Cannot input answer

## Screenshots

_[If applicable, provide screenshots illustrating the issue.]_

## Environment

- **Django Version:** _[Django version you're using, e.g., 3.2.1]_
- **Python Version:** _[Python version, e.g., 3.9]_
- **Operating System:** _[Your OS, e.g., Windows 10, Ubuntu 20.04]_
- **Browser:** _[If applicable, specify the browser and version you're using.]_

## Additional Information

_[Any other relevant information, logs, error messages, or context that might help in understanding and fixing the issue.]_

## Possible Solution

_[If you have any ideas or suggestions on how to fix the issue, feel free to provide them here. This is optional.]_

## Labels

_[If your project uses labels, suggest any labels that might apply to this issue, such as 'bug', 'needs investigation', etc.]_

## Priority

_[Specify the priority level for this issue, such as 'high', 'medium', 'low', etc.]_

## Assignees

_[If you want to suggest an assignee or tag a specific person to look into this issue, mention their GitHub username here.]_

## Related Issues

_[If there are any related issues or pull requests, mention them here. This is optional.]_

**Note:** _Remember to search through existing issues before submitting a new one to ensure that the issue hasn't been reported already. Provide as much information as possible to help the maintainers understand and address the problem effectively._

**Comment by horilla-opensource** [comment] 2024-11-15 05:38
Hi @o0alvin0o ,

The issue is now fixed in the master. Please pull the latest code and try again.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-11-22 09:43
Hi @o0alvin0o ,
We are closing this issue due to inactivity. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**

**Closed by horilla-opensource** 2024-11-22 09:43 UTC
