### ISSUE TITLE
Super user Issue

### ISSUE THREAD

**Issue by Kushaldotel** [horilla-opensource/horilla#99] opened 2024-03-03 15:13 UTC
When we create a super user and try to log in as a super user in our portal this issue is raised:
  File "E:\Products\horilla\base\views.py", line 197, in login_user
    if user.employee_get.is_active == False:
       ^^^^^^^^^^^^^^^^^
  File "E:\Products\horilla\myenv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 492, in __get__
    raise self.RelatedObjectDoesNotExist(
django.contrib.auth.models.User.employee_get.RelatedObjectDoesNotExist: User has no employee_get.
[03/Mar/2024 20:57:17] "POST /login/?next=/employee/rotating-work-type-assign/ HTTP/1.1" 500 74429
![image](https://github.com/horilla-opensource/horilla/assets/114340617/46fdd4b3-3a63-4302-8361-a370d838629f)

**Comment by horilla-opensource** [comment] 2024-03-04 04:26
Hi @Kushaldotel ,
How did you create the superuser?
Using the createsuperuser or createhorillauser?

With Regards,
**Team Horilla**

**Comment by Kushaldotel** [comment] 2024-03-04 05:47
I made using superuser. This command still exists

**Comment by horilla-opensource** [comment] 2024-03-04 05:54
Oh, Okay.
The issue is because you have created the user using the superuser command, which does create a user account, but doesn't create an employee in the database which caused the issue.
We'll comment put the createsuperuser command from the system.
To have the system running smoothly, please create the superuser using the _createhorillauser_ command.
Let us know if that fixed your issue.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-03-19 05:14
Hi @Kushaldotel ,
Does the above solution fixed the issue? If so, can we please close this issue?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-04-22 08:59
Hi @Kushaldotel ,
Any updates?

With Regards,
**Team Horilla**

**Comment by Kushaldotel** [comment] 2024-05-05 11:46
yes it worked as you said

**Comment by horilla-opensource** [comment] 2024-05-06 07:26
Thanks for the update.
We are closing the issue as its solved.

With Regards, 
**Team Horilla**

**Closed by horilla-opensource** 2024-05-06 07:26 UTC
