### ISSUE TITLE
[BUG]  Strange calculation of the working hours.

### ISSUE THREAD

**Issue by Hamza2961** [horilla-opensource/horilla#81] opened 2024-01-25 16:02 UTC
# Bug Report

## Description

The working hours seem to be wrongly calculated, According to my check in today, my working hours should have been 7 hours and 20 minutes approximately, but the current working hours count says, I have already been working since 14 hours.
## Expected Behavior

Correct hours calculation, with respect to the check ins and check outs.

## Actual Behavior

The timer calculates the time correctly, if the window is kept open, but as soon as the user refreshes or reloads the page, or maybe closes the window and reopens it, the timer shows the wrong time.

## Screenshots

![image](https://github.com/horilla-opensource/horilla/assets/136076667/1cb1a120-8d3b-48a5-ab9d-f690a7d98578)
Before Reload 

![image](https://github.com/horilla-opensource/horilla/assets/136076667/525a8a24-2a63-474e-b11b-ea99d7f34ece)
After reload 

## Additional Information

As far as I examined, something triggers the timer to calculate the time more or less 5x times the normal calculation. I don't know if this helps, but I used a stopwatch to examine the exact factor by which the time-calculation speeds up. 
The Scenario:
I reloaded the page, and it was 15:11:40, and exactly after 1 minute, i refreshed the page (again) , and the timer shows 15:16:42. Approximately 5 Minutes. (That's not always the case, as in the above screenshots. But mostly this is what happens.)

## Priority

High

**Comment by horilla-opensource** [comment] 2024-02-05 08:37
Hi @Hamza2961 ,
Could you please check in the attendance entries if there are any duplicate entries occurred in the system?

**Comment by Hamza2961** [comment] 2024-02-07 07:55
> Hi @Hamza2961 , Could you please check in the attendance entries if there are any duplicate entries occurred in the system?

As far as I see, no.

**Comment by horilla-opensource** [comment] 2024-03-19 05:12
Hi @Hamza2961 ,
Were you able to test out the solution?
If the issue is fixed, can we please close this issue?

With Regards,
**Team Horilla**

**Comment by Hamza2961** [comment] 2024-03-20 08:38
> Hi @Hamza2961 , Were you able to test out the solution? If the issue is fixed, can we please close this issue?
> 
> With Regards, **Team Horilla**

Hi, yes, the issue seems to be fixed.

**Comment by horilla-opensource** [comment] 2024-03-20 16:13
Hi @Hamza2961 ,
Can we close the issue?

With Regards,
**Team Horilla**

**Closed** 2024-04-22 08:55 UTC
