### ISSUE TITLE
Suggestions to improve of the request attendance views

### ISSUE THREAD

**Issue by dot3media** [horilla-opensource/horilla#62] opened 2023-12-06 09:57 UTC
# Feature Request

### Requested Attendances

In addition to the changed fields, the new values should also be displayed in the list view, as this is the only way to see at a glance whether the correct times are now being recorded.

### Presence times

The table view should be displayed more compactly, as it is only reasonably clear on very large screens and the application buttons scroll out of sight.

## Proposed Solution

* Hide employee column if you are logged in as an employee.
* Date in short form and without a break (30.11.2023 instead of November 30, 2023).
* In-date is often sufficient. It is better to record times over several days on a daily basis.
* Then the check-in and check-out times can also be displayed directly next to each other.
* Possibly display shift and working method above the table with employee data if they cannot change daily.
* Display absences as well as overtime.
* Never let the request button scroll away.
* For all fields, check again whether the order really makes sense for an overview.
* Display request status if a request has been filed for an entry.

**Comment by borishinzer** [comment] 2023-12-22 09:23
It would be great if the columns in the different views can be hidden (similar to group function)

**Comment by horilla-opensource** [comment] 2023-12-22 09:25
Yes, we are working on the system to make the columns hidden based on the users need.
Will update the solution to this asap.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-01-29 08:10
Hi @dot3media @borishinzer ,
We have added the option for toggling columns in the list view for the attendance tables.
Users can now be able to toggle the columns that they require in the list view.
<img width="1470" alt="Screenshot 2024-01-29 at 1 39 23 PM" src="https://github.com/horilla-opensource/horilla/assets/131998600/2c809068-b7a1-471f-9412-0819246639b1">

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-02-09 11:36
Hi @dot3media ,
Thanks. Glad to hear.
If the issue is solved from your side, can we close this issue?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-03-19 05:06
Hi @dot3media ,
Any updates on testing the solution, if it is okay we can please close the issue?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-05-18 15:26
Hi @dot3media ,
Closing this issue as the fix has been published.

With Regards,
**Team Horilla**

**Closed by horilla-opensource** 2024-05-18 15:26 UTC
