### ISSUE TITLE
Employee > Leave Days (vacations) calculated wrong

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#82] opened 2024-01-30 08:23 UTC
# Bug Report
The amount of total available days is wrong. As you can see we have a total of 28 days per year. 
The employee started with -2 days leaving 26 days for the full year. 
If you calculate the amount the available days should be 0. 

<img width="1290" alt="Bildschirmfoto 2024-01-30 um 09 19 38" src="https://github.com/horilla-opensource/horilla/assets/10340538/0669606c-5725-4a24-9f3c-04e675e22c50">

**Comment by borishinzer** [comment] 2024-01-30 09:04
From the screenshot you can see, we have 28 leave days per year (vacation, holidays). As this employee started with -2 days, he had 26 days available in 2023.  Now please check the "Vacation 28 days (FTE)". There is still 7 leave days mentioned, although the total amount of approved leave days is 26. 

Expected: Would be 0 days left.

**Comment by horilla-opensource** [comment] 2024-02-06 06:59
Hi @borishinzer ,
We have added the solution for the issue in the commit [[FIX] LEAVE: -ve value storing issue in available leave](https://github.com/horilla-opensource/horilla/commit/86c5e3cce891ca859ee58938dd2e99bfc273d451)
Please check and let us know if the issue is not solved.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-03-19 05:13
Hi @borishinzer ,
Were you able to test it out?
If the issue is fixed, can we please close the issue?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-04-22 08:55
Hi @borishinzer ,
Any updates?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-05-18 15:30
Hi @borishinzer ,
We are closing this issue as the fix has been added. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**

**Closed by horilla-opensource** 2024-05-18 15:30 UTC
