### ISSUE TITLE
[BUG] New user can't get password link

### ISSUE THREAD

**Issue by borishinzer** [horilla-opensource/horilla#101] opened 2024-03-04 08:37 UTC
# Bug Report
I created a new user. And when the user requests the password link, he gets the error message "'Anonymoususer' object has no attribute employee_get"

**Comment by horilla-opensource** [comment] 2024-03-04 08:43
#98

**Comment by horilla-opensource** [comment] 2024-03-04 09:14
Hi @borishinzer ,
The solution for the issue is updated in the commit [[FIX] BASE: Bug fix in ConfiguredEmailBackend class by updating condition to check request.user exist](https://github.com/horilla-opensource/horilla/commit/d9b73ac833c21140b8143504720fff094887c999).

Please check with the latest code and let us know if this fixed the issue.

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-03-19 05:14
Hi @borishinzer ,
Were you able to test out the solution?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-04-22 08:59
Hi @borishinzer ,
Any updates?

With Regards,
**Team Horilla**

**Comment by horilla-opensource** [comment] 2024-05-18 15:31
Hi @borishinzer  ,
We are closing this issue as the fix has been added. It seems that there hasn't been any recent activity or discussion, and we believe it may have been resolved or is no longer relevant. 
If you feel this issue is still important and should be addressed, please feel free to reopen it or create a new issue with updated details. 

With Regards,
**Team Horilla**

**Closed by horilla-opensource** 2024-05-18 15:31 UTC
