### ISSUE TITLE
Candidate creation form not gets submitted

### ISSUE THREAD

**Issue by dKarths** [horilla-opensource/horilla#216] opened 2024-06-23 11:09 UTC
# Bug Report

Candidate creation form not gets submitted

## Steps to Reproduce

1.Recruitment - Create candidate and add mandatory fields details. Upload resume and submit

## Actual Behavior

Form not gets submitted .

Log message : Not Found : /templates/sidebar.html

**Comment by dKarths** [comment] 2024-06-24 06:01
Horilla    = 1.1.0 
Ubuntu  = 24.04 LTS
Chrome Version 126.0.6478.115 (64-bit)

**Comment by dKarths** [comment] 2024-06-24 06:04
![image](https://github.com/horilla-opensource/horilla/assets/173607064/3b4bd5ee-7ef5-47ea-9a68-df8c77ed5158)

**Comment by horilla-opensource** [comment] 2024-06-24 06:09
Hi @dKarths ,
You can avoid the sidebar.html not found error.
That won't cause the issue with the form submission.
Can you try the submission by making the debug as True and get the error log ?
May be the issue is with the nginx configuration? Can you try it again by adding the **client_max_body_size 100M;** in the server block ?

With Regards,
**Team Horilla**

**Comment by dKarths** [comment] 2024-06-26 10:25
We have configured nginx with client_max_body_size 100M;
 Logs screenshot attached with  Debug as True

![Logs](https://github.com/horilla-opensource/horilla/assets/173607064/4265e6af-dcf2-4894-8e82-8a9c3f1bb61a)

**Comment by horilla-opensource** [comment] 2024-06-26 10:44
Hi @dKarths ,
From the current context, we are not able to reproduce or pin point the issue.
Are you trying to create the candidate directly from the candidate view or open recruitment page ?

With Regards,
**Team Horilla**

**Comment by dKarths** [comment] 2024-06-26 10:52
I have given the exact steps.

1.Navigate to Recruitment
2.Navigate to Candidates
3. Click on Create candidate
4. Enter all the mandatory details and upload Resume(pdf file)
5. Submit the page

actual Result
Page not get submitted. Error thrown as ''This field is required'

Thanks,
Karthi

**Comment by horilla-opensource** [comment] 2024-06-26 11:05
Hi @dKarths ,
The image is also a mandatory field. From the context I think that you haven't added the candidate image.
Please add a candidate image and try again.

With Regards,
**Team Horilla**

**Comment by dKarths** [comment] 2024-06-26 14:18
Issue solved after adding candidate image.
Thanks for the  support and prompt reply

Regards,
Karthi

**Comment by horilla-opensource** [comment] 2024-06-26 15:43
Can we close this issue then?

**Comment by dKarths** [comment] 2024-06-26 16:02
Yes , Issue can be closed

**Closed** 2024-06-26 18:33 UTC
